"""
A loaded :class:`DataModel` written back out as ``models/<name>.yaml``.

``tracebi migrate model`` uses this to convert a Python model. The YAML is
built from the model's public surface (``info()``, ``measures()``,
``connectors()``) and then compiled again and compared with the original, so a
conversion either reproduces the model or is refused with the reason. The
Python file's comments are not carried over: they are not part of the loaded
model.
"""

from __future__ import annotations

import dataclasses
import tempfile
from pathlib import Path
from typing import Any

from tracebi.model.data_model import DataModel
from tracebi.model.model_spec import load_model_spec

_MEASURE_ORDER = ("column", "agg", "expr", "ratio", "share", "rank", "running",
                  "partition_by", "period_end", "offset", "growth", "to_date",
                  "description", "format", "allow_rate_agg")

_HEADER = """\
# {name}: generated by `tracebi migrate model` from models/{name}.py.
# Comments in the Python file are not carried over; add the reasons back here.
# While models/{name}.py exists it wins over this file: delete one of them.
"""

_SECTIONS = (
    ("connectors", "where the tables live (a DuckDB file inside the project)"),
    ("tables", "each table the phase-1 transform sank, by its warehouse name"),
    ("relationships", "named joins between tables"),
    ("dimensions", "the descriptive tables (key column, attributes to slice by)"),
    ("facts", "the event tables (numeric columns, key to each dimension)"),
    ("time_grains", "derived date attributes (group by month, quarter, ...)"),
    ("value_bins", "derived bands over a numeric column"),
    ("measures", "the named vocabulary reports ask for"),
)


class ModelMigrationError(ValueError):
    """A model that cannot be written as YAML, with the reason."""


def _dumper():
    """Block style throughout, a list of plain values on one line, and list
    items indented under their key, which is how people write a model."""
    import yaml

    class _Dumper(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    def _list(dumper, data):
        flat = not any(isinstance(i, (dict, list)) for i in data)
        return dumper.represent_sequence("tag:yaml.org,2002:seq", data,
                                         flow_style=flat)

    _Dumper.add_representer(list, _list)
    return _Dumper


def _connector(c, root: Path) -> dict:
    from tracebi.connectors.duckdb_connector import DuckDBConnector

    if not isinstance(c, DuckDBConnector):
        raise ModelMigrationError(
            f"connector '{c.name}' is a {type(c).__name__}; a YAML model "
            f"declares a DuckDB file, or reuses models/_connections/<x>.py "
            f"written by `tracebi connect` (add it there, then write "
            f"`connection: <x>` by hand)")
    described = c.describe()
    if described.get("directory"):
        raise ModelMigrationError(
            f"connector '{c.name}' reads a directory of files; a YAML "
            f"connector declares one DuckDB file")
    database = str(described["database"])
    if database == ":memory:" or not database:
        raise ModelMigrationError(
            f"connector '{c.name}' is an in-memory database; there is no file "
            f"to name")
    try:
        rel = Path(database).resolve().relative_to(root.resolve())
    except ValueError:
        raise ModelMigrationError(
            f"connector '{c.name}' database {database!r} is outside the "
            f"project ({root}); a YAML model keeps it inside") from None
    return {"name": c.name, "type": "duckdb", "database": rel.as_posix()}


def _measure(m: Any) -> dict:
    out: dict = {"name": m.name}
    for key in _MEASURE_ORDER:
        value = getattr(m, key)
        if value in (None, "", (), False):
            continue
        out[key] = list(value) if isinstance(value, tuple) else value
    return out


def _document(model: DataModel, root: Path) -> dict:
    info = model.info()
    doc: dict = {"name": model.name}
    doc["connectors"] = [_connector(c, root) for c in model.connectors()]
    doc["tables"] = [{k: t[k] for k in ("name", "connector", "source")}
                     for t in info["tables"]]
    if info["relationships"]:
        doc["relationships"] = [
            {"name": r["name"], "left_table": r["left_table"],
             "right_table": r["right_table"], "left_key": r["left_key"],
             **({"right_key": r["right_key"]}
                if r["right_key"] != r["left_key"] else {}),
             **({"how": r["how"]} if r["how"] != "left" else {})}
            for r in info["relationships"]]
    if info["dimensions"]:
        doc["dimensions"] = [
            {"name": d["name"], "table": d["table"], "key": d["key"],
             **({"attributes": d["attributes"]} if d["attributes"] else {})}
            for d in info["dimensions"]]
    if info["facts"]:
        doc["facts"] = [
            {"name": f["name"], "table": f["table"], "measures": f["measures"],
             **({"foreign_keys": f["foreign_keys"]} if f["foreign_keys"] else {})}
            for f in info["facts"]]
    grains, bins = [], []
    for d in info["dimensions"]:
        for name, v in d.get("derived", {}).items():
            where = {"dimension": d["name"], "name": name, "source": v["of"]}
            if v["kind"] == "date_trunc":
                grains.append({**where, "grain": v["grain"]})
            elif v["kind"] == "bin":
                bins.append({**where, "edges": v["edges"], "labels": v["bands"]})
            else:
                raise ModelMigrationError(
                    f"dimension '{d['name']}' attribute '{name}' is a "
                    f"'{v['kind']}' derivation, which a YAML model cannot "
                    f"declare")
    if grains:
        doc["time_grains"] = grains
    if bins:
        doc["value_bins"] = bins
    if model.measures():
        doc["measures"] = [_measure(m) for m in model.measures().values()]
    return doc


def _shape(model: DataModel) -> dict:
    info = model.info()
    return {
        "tables": [{k: t[k] for k in ("name", "connector", "source")}
                   for t in info["tables"]],
        "relationships": info["relationships"],
        "facts": [{k: v for k, v in f.items() if k != "runnable_measures"}
                  for f in info["facts"]],
        "dimensions": info["dimensions"],
        "measures": {n: dataclasses.asdict(m) for n, m in model.measures().items()},
    }


def model_to_yaml(model: DataModel, stem: str, root: "str | Path") -> str:
    """The YAML text for *model*, to live at ``<root>/models/<stem>.yaml``.

    Raises :class:`ModelMigrationError` when the model cannot be expressed or
    the YAML does not compile back to the same model.
    """
    import yaml

    dumper = _dumper()
    root = Path(root)
    if model.name != stem:
        raise ModelMigrationError(
            f"the model is named {model.name!r} but the file is {stem!r}; a "
            f"YAML model's name equals its file name, so rename one first "
            f"(the name is part of every query's receipt)")
    doc = _document(model, root)

    parts = [_HEADER.format(name=stem), f"name: {stem}\n"]
    for key, blurb in _SECTIONS:
        if key in doc:
            parts.append(f"# {key}: {blurb}\n" + yaml.dump(
                {key: doc[key]}, Dumper=dumper, sort_keys=False, width=100,
                allow_unicode=True))
    text = "\n".join(parts)

    with tempfile.TemporaryDirectory() as tmp:
        probe = Path(tmp) / f"{stem}.yaml"
        probe.write_text(text, encoding="utf-8")
        try:
            rebuilt = load_model_spec(probe, root=root)
        except Exception as exc:  # noqa: BLE001 — the reason is the answer
            raise ModelMigrationError(
                f"the generated YAML does not compile: {exc}. A measure "
                f"that needed allow_additive=True is the usual cause; add it "
                f"to the YAML by hand") from exc
    try:
        same = _shape(rebuilt) == _shape(model)
    finally:
        rebuilt.disconnect()
    if not same:
        raise ModelMigrationError(
            "the generated YAML compiles to a different model than the "
            "Python file; nothing was written")
    return text
