"""Baseline: the runner tables as today's code leaves them after startup.

An existing database already has these tables (``CREATE TABLE IF NOT EXISTS``
is a no-op there). Actor columns are in this baseline because startup
reconciliation has been adding them; a database from before that still gains
them from ``_add_missing_run_columns``.

Revision ID: 0001
Revises:
Create Date: 2026-10-03
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

# AUTOINCREMENT is SQLite-only. Postgres uses IDENTITY. Same split the
# runner used before Alembic owned this schema.
_PK = {
    "sqlite": "INTEGER PRIMARY KEY AUTOINCREMENT",
    "postgresql": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
}
_PK_DEFAULT = "INTEGER PRIMARY KEY"

_TABLES = (
    ("tracebi_layers", """CREATE TABLE IF NOT EXISTS tracebi_layers (
        id          {pk},
        name        TEXT    UNIQUE NOT NULL,
        layer_type  TEXT    NOT NULL,
        schedule    TEXT,
        source_table TEXT,
        sink_table  TEXT,
        depends_on  TEXT,
        created_at  TEXT    NOT NULL
    )"""),
    ("tracebi_runs", """CREATE TABLE IF NOT EXISTS tracebi_runs (
        id              {pk},
        layer_name      TEXT NOT NULL,
        layer_type      TEXT NOT NULL,
        started_at      TEXT NOT NULL,
        completed_at    TEXT,
        status          TEXT NOT NULL,
        rows_in         INTEGER,
        rows_out        INTEGER,
        upstream_run_id INTEGER,
        error_message   TEXT,
        actor           TEXT,
        actor_role      TEXT
    )"""),
    ("tracebi_schemas", """CREATE TABLE IF NOT EXISTS tracebi_schemas (
        id          {pk},
        schema_name TEXT NOT NULL,
        model_name  TEXT NOT NULL,
        created_at  TEXT NOT NULL
    )"""),
    ("tracebi_dimensions", """CREATE TABLE IF NOT EXISTS tracebi_dimensions (
        id          {pk},
        schema_id   INTEGER NOT NULL,
        dim_name    TEXT NOT NULL,
        table_name  TEXT NOT NULL,
        key_col     TEXT NOT NULL,
        attributes  TEXT
    )"""),
    ("tracebi_facts", """CREATE TABLE IF NOT EXISTS tracebi_facts (
        id          {pk},
        schema_id   INTEGER NOT NULL,
        fact_name   TEXT NOT NULL,
        table_name  TEXT NOT NULL,
        measures    TEXT NOT NULL,
        foreign_keys TEXT
    )"""),
    ("tracebi_relationships", """CREATE TABLE IF NOT EXISTS tracebi_relationships (
        id          {pk},
        model_name  TEXT NOT NULL,
        rel_name    TEXT NOT NULL,
        left_table  TEXT NOT NULL,
        right_table TEXT NOT NULL,
        left_key    TEXT NOT NULL,
        right_key   TEXT NOT NULL,
        how         TEXT NOT NULL DEFAULT 'left'
    )"""),
)


def upgrade() -> None:
    pk = _PK.get(op.get_bind().dialect.name, _PK_DEFAULT)
    for _name, sql in _TABLES:
        op.execute(sql.format(pk=pk))


def downgrade() -> None:
    for name, _sql in reversed(_TABLES):
        op.execute(f"DROP TABLE IF EXISTS {name}")
