"""What an MCP session did, for its private watch link.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08
"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None

_PK = {
    "sqlite": "INTEGER PRIMARY KEY AUTOINCREMENT",
    "postgresql": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
}


def upgrade() -> None:
    bind = op.get_bind()
    if "tracebi_live_events" in sa.inspect(bind).get_table_names():
        return
    pk = _PK.get(bind.dialect.name, "INTEGER PRIMARY KEY")
    op.execute(f"""CREATE TABLE tracebi_live_events (
        id      {pk},
        watch   TEXT NOT NULL,
        at      TEXT NOT NULL,
        entry   TEXT NOT NULL
    )""")
    op.create_index("ix_tracebi_live_events_watch", "tracebi_live_events", ["watch", "id"])


def downgrade() -> None:
    op.drop_index("ix_tracebi_live_events_watch", table_name="tracebi_live_events")
    op.drop_table("tracebi_live_events")
